name: Toothpick Scan

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  scan:
    name: Run Toothpick Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Toothpick
        run: |
          python -m pip install --upgrade pip
          pip install toothpick

      - name: Run Toothpick
        run: |
          toothpick scan .
        continue-on-error: true  # Continue even if Toothpick finds issues

      - name: Upload Toothpick Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: toothpick-report
          path: .toothpick/logs  # Assuming Toothpick stores logs here
